AWSTemplateFormatVersion: '2010-09-09'
Description: 'IAM role and policy for Terraform state access'

Parameters:
  ProjectName:
    Type: String
    Description: Name of the project
    Default: terraform-core-aws
  
  Organization:
    Type: String
    Description: Name of the organization
    Default: faccomichele
  
  Environment:
    Type: String
    Description: Environment/Workspace (dev, stg, prod)
    AllowedValues:
      - dev
      - stg
      - prod
    Default: dev
  
  AccountId:
    Type: String
    Description: AWS Account ID
  
  StateBucketArn:
    Type: String
    Description: ARN of the S3 bucket for Terraform state

Resources:
  TerraformStateRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-state-files-${Environment}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Ref AccountId
            Action: sts:AssumeRole
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Organization
          Value: !Ref Organization
        - Key: Environment
          Value: !Ref Environment
        - Key: RepositoryURL
          Value: !Sub 'https://github.com/${Organization}/${ProjectName}'
        - Key: Automation
          Value: CloudFormation
        - Key: RepositoryPath
          Value: '.'
        - Key: RepositoryFile
          Value: cloudformation/nested/iam-state-role.yaml
        - Key: Description
          Value: IAM role for accessing Terraform state files

  TerraformStatePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: terraform-state-files-policy
      Roles:
        - !Ref TerraformStateRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: ListObjectsInBucket
            Effect: Allow
            Action:
              - s3:ListBucket
            Resource: !Ref StateBucketArn
          - Sid: AllObjectActions
            Effect: Allow
            Action:
              - s3:GetObject
              - s3:PutObject
              - s3:DeleteObject
            Resource: !Sub '${StateBucketArn}/*'

Outputs:
  RoleArn:
    Description: ARN of the IAM role for Terraform state access
    Value: !GetAtt TerraformStateRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-RoleArn'
  
  RoleName:
    Description: Name of the IAM role for Terraform state access
    Value: !Ref TerraformStateRole
    Export:
      Name: !Sub '${AWS::StackName}-RoleName'
