AWSTemplateFormatVersion: '2010-09-09'
Description: 'S3 bucket for Terraform state files with versioning, encryption, and lifecycle policies'

Parameters:
  ProjectName:
    Type: String
    Description: Name of the project
    Default: terraform-core-aws
  
  Organization:
    Type: String
    Description: Name of the organization
    Default: faccomichele
  
  Environment:
    Type: String
    Description: Environment/Workspace (dev, stg, prod)
    AllowedValues:
      - dev
      - stg
      - prod
    Default: dev
  
  AccountId:
    Type: String
    Description: AWS Account ID

Resources:
  TerraformStateBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${ProjectName}-state-files-${Environment}-${AccountId}'
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
            BucketKeyEnabled: true
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: terraform-state-files-lifecycle
            Status: Enabled
            NoncurrentVersionExpiration:
              NoncurrentDays: 30
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Organization
          Value: !Ref Organization
        - Key: Environment
          Value: !Ref Environment
        - Key: RepositoryURL
          Value: !Sub 'https://github.com/${Organization}/${ProjectName}'
        - Key: Automation
          Value: CloudFormation
        - Key: RepositoryPath
          Value: '.'
        - Key: RepositoryFile
          Value: cloudformation/nested/s3-state-bucket.yaml
        - Key: Name
          Value: !Sub '${ProjectName}-state-files-${Environment}'
        - Key: Description
          Value: S3 bucket for storing Terraform state files

Outputs:
  BucketName:
    Description: Name of the S3 bucket for Terraform state
    Value: !Ref TerraformStateBucket
    Export:
      Name: !Sub '${AWS::StackName}-BucketName'
  
  BucketArn:
    Description: ARN of the S3 bucket for Terraform state
    Value: !GetAtt TerraformStateBucket.Arn
    Export:
      Name: !Sub '${AWS::StackName}-BucketArn'
