AWSTemplateFormatVersion: '2010-09-09'
Description: 'Terraform State Management Infrastructure - Core resources (S3, IAM, and SSM in a single stack)'

# Stack Name: terraform-core-backend-setup-${Environment}
# Deploy this stack only in the central account and once for each environment
# This stack needs to be updated every time a new account is added

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Project Configuration
        Parameters:
          - ProjectName
          - Organization
          - Environment
          - AllowedAssumeRoleAccountIDs
    ParameterLabels:
      ProjectName:
        default: Project Name
      Organization:
        default: Organization Name
      Environment:
        default: Environment/Workspace
      AllowedAssumeRoleAccountIDs:
        default: Comma-separated list of Account IDs allowed to assume the Terraform state role

Parameters:
  ProjectName:
    Type: String
    Description: Name of the project
    Default: terraform-core-aws
    MinLength: 1
    MaxLength: 63
    AllowedPattern: ^[a-z0-9-]+$
    ConstraintDescription: Must be lowercase alphanumeric with hyphens only
  
  Organization:
    Type: String
    Description: Name of the organization
    Default: faccomichele
    MinLength: 1
    MaxLength: 63
    AllowedPattern: ^[a-z0-9-]+$
    ConstraintDescription: Must be lowercase alphanumeric with hyphens only
  
  Environment:
    Type: String
    Description: Environment/Workspace (dev, stg, prod)
    AllowedValues:
      - dev
      - stg
      - prod
    Default: dev

  AllowedAssumeRoleAccountIDs:
    Type: CommaDelimitedList
    Description: >-
      Comma-separated list of Account IDs allowed to assume the
      Terraform state role (for example: 123456789012,123456789013). Each
      account ID will allow any principal in that account to assume the role.

Resources:
  # S3 bucket for Terraform state files
  TerraformStateBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${ProjectName}-state-files-${Environment}-${AWS::AccountId}'
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
            BucketKeyEnabled: true
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: terraform-state-files-lifecycle
            Status: Enabled
            NoncurrentVersionExpiration:
              NoncurrentDays: 30
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Organization
          Value: !Ref Organization
        - Key: Environment
          Value: !Ref Environment
        - Key: RepositoryURL
          Value: !Sub 'https://github.com/${Organization}/${ProjectName}'
        - Key: Automation
          Value: CloudFormation
        - Key: RepositoryPath
          Value: cloudformation
        - Key: RepositoryFile
          Value: backend-setup.yaml
        - Key: Name
          Value: !Sub '${ProjectName}-state-files-${Environment}'
        - Key: Description
          Value: S3 bucket for storing Terraform state files
        - Key: Region
          Value: !Ref 'AWS::Region'

  # IAM role for Terraform state access
  TerraformStateRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Split
                - ","
                - !Sub
                  - "arn:aws:iam::${JoinedAccounts}:root"
                  - JoinedAccounts: !Join
                      - ":root,arn:aws:iam::"
                      - !Ref AllowedAssumeRoleAccountIDs
            Action: sts:AssumeRole
      Policies:
        - PolicyName: terraform-state-files-inline-policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: ListObjectsInBucket
                Effect: Allow
                Action:
                  - s3:ListBucket
                Resource: !GetAtt TerraformStateBucket.Arn
              - Sid: AllObjectActions
                Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                Resource: !Sub '${TerraformStateBucket.Arn}/*'
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Organization
          Value: !Ref Organization
        - Key: Environment
          Value: !Ref Environment
        - Key: RepositoryURL
          Value: !Sub 'https://github.com/${Organization}/${ProjectName}'
        - Key: Automation
          Value: CloudFormation
        - Key: RepositoryPath
          Value: cloudformation
        - Key: RepositoryFile
          Value: backend-setup.yaml
        - Key: Description
          Value: IAM role for accessing Terraform state files
        - Key: Region
          Value: !Ref 'AWS::Region'

Outputs:
  AwsId:
    Value: !Sub '/manual/global/central-account/account-id = ${AWS::AccountId}'
  RoleSecret:
    Value:
      Fn::Sub:
        - '/manual/${Environment}/terraform/state-file/role-secret = ${SecretValue}'
        - SecretValue:
            Fn::Select:
              - 6
              - Fn::Split:
                  - "-"
                  - !GetAtt TerraformStateRole.Arn
