AWSTemplateFormatVersion: '2010-09-09'
Description: 'GitHub Actions OIDC Identity Provider - Enables secure, keyless authentication for GitHub Actions workflows'

# Stack Name: terraform-core-github-identity-provider
# Deploy this stack once per account

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Project Configuration
        Parameters:
          - ProjectName
          - Organization
    ParameterLabels:
      ProjectName:
        default: Project Name
      Organization:
        default: Organization Name

Parameters:
  ProjectName:
    Type: String
    Description: Name of the project
    Default: terraform-core-aws
    MinLength: 1
    MaxLength: 63
    AllowedPattern: ^[a-z0-9-]+$
    ConstraintDescription: Must be lowercase alphanumeric with hyphens only
  
  Organization:
    Type: String
    Description: Name of the organization
    Default: faccomichele
    MinLength: 1
    MaxLength: 63
    AllowedPattern: ^[a-z0-9-]+$
    ConstraintDescription: Must be lowercase alphanumeric with hyphens only

Resources:
  # IAM OIDC Identity Provider for GitHub Actions
  GitHubOIDCProvider:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ClientIdList:
        - sts.amazonaws.com
      ThumbprintList:
        - 6938fd4d98bab03faadb97b34396831e3780aea1
        - 1c58a3a8518e8759bf075b76b750d4f2df264fcd
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Organization
          Value: !Ref Organization
        - Key: RepositoryURL
          Value: !Sub 'https://github.com/${Organization}/${ProjectName}'
        - Key: Automation
          Value: CloudFormation
        - Key: RepositoryPath
          Value: cloudformation
        - Key: RepositoryFile
          Value: github-identity-provider.yaml
        - Key: Name
          Value: terraform-core-github-identity-provider
        - Key: Description
          Value: OIDC provider for GitHub Actions authentication
        - Key: Region
          Value: !Ref 'AWS::Region'