AWSTemplateFormatVersion: '2010-09-09'
Description: 'Creates an IAM managed policies for GitHub Actions (OIDC) workflows that grants read access to the Terraform backend configuration and permission to assume the Terraform state role.'

# Stack Name: terraform-core-github-terraform-policies-${Environment}
# Deploy this stack once for account/environment combination

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
        - Label:
            default: Project Configuration
          Parameters:
            - ProjectName
            - Organization
            - Environment
    ParameterLabels:
      ProjectName:
        default: Project Name
      Organization:
        default: Organization Name
      Environment:
        default: Environment/Workspace

Parameters:
  ProjectName:
    Type: String
    Description: Name of the project
    Default: terraform-core-aws
    MinLength: 1
    MaxLength: 63
    AllowedPattern: ^[a-z0-9-]+$
    ConstraintDescription: Must be lowercase alphanumeric with hyphens only
  
  Organization:
    Type: String
    Description: Name of the organization
    Default: faccomichele
    MinLength: 1
    MaxLength: 63
    AllowedPattern: ^[a-z0-9-]+$
    ConstraintDescription: Must be lowercase alphanumeric with hyphens only

  Environment:
    Type: String
    Description: Environment/Workspace (dev, stg, prod)
    AllowedValues:
      - dev
      - stg
      - prod
    Default: dev

Resources:
  # Standalone IAM managed policy for SSM parameter read access
  TerraformStateFileAccessPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub '${ProjectName}-tf-access-${Environment}'
      Description: Allows access to Terraform backend configuration
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AssumeRoleTerraformStateRole
            Effect: Allow
            Action:
              - sts:AssumeRole
            Resource: !Sub 'arn:aws:iam::{{resolve:ssm:/manual/global/central-account/account-id}}:role/terraform-core-backend-setup-${Environment}-TerraformStateRole-{{resolve:ssm:/manual/global/terraform/state-file/role-secret}}'

    # Managed policy for SSM Parameter Store access
  # Grants access across all regions (*) to support multi-region Terraform deployments
  SSMParameterReadPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub '${ProjectName}-ssm-read-${Environment}'
      Description: Grants read access to SSM parameters for Terraform state configuration
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: SSMParameterRead
            Effect: Allow
            Action:
              - ssm:GetParameter
              - ssm:GetParameters
            Resource:
              - !Sub 'arn:aws:ssm:*:${AWS::AccountId}:parameter/manual/${Environment}/terraform/state-file/role-secret'
              - !Sub 'arn:aws:ssm:*:${AWS::AccountId}:parameter/manual/global/central-account/account-id'
