AWSTemplateFormatVersion: '2010-09-09'
Description: 'GitHub Actions IAM Role - Template for deploying repository-specific GitHub Actions roles that assume the shared OIDC provider'

# Stack Name: github-role-for-<repo-name>

# DEPLOYMENT INSTRUCTIONS:
# PREREQUISITE: The GitHub OIDC provider must be deployed first using the github-identity-provider.yaml template.
#               This creates the shared OIDC provider that this role will reference.
#               Deploy it with stack name 'github-identity-provider' (or update OIDCProviderStackName parameter below).
# 
# 1. Copy this template to your target repository
# 2. Update the ProjectName parameter default to match your repository name
# 3. Optionally adjust Environment parameter if needed
# 4. Add additional managed policies or inline policies as required for your application
# 5. Deploy with: aws cloudformation create-stack --stack-name github-role-for-<repo-name> --template-body file://github-iam-role-template.yaml --capabilities CAPABILITY_NAMED_IAM

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Repository Configuration
        Parameters:
          - Organization
          - ProjectName
          - Environment
      - Label:
          default: Infrastructure References
        Parameters:
          - OIDCProviderStackName
          - TerraformAccessPolicyAccountID
    ParameterLabels:
      Organization:
        default: GitHub Organization
      ProjectName:
        default: Repository Name
      Environment:
        default: Environment
      OIDCProviderStackName:
        default: OIDC Provider Stack Name
      TerraformAccessPolicyAccountID:
        default: Terraform Access Policy Account ID

Parameters:
  Organization:
    Type: String
    Description: GitHub organization name
    Default: faccomichele
    MinLength: 1
    MaxLength: 63
    AllowedPattern: ^[a-z0-9-]+$
    ConstraintDescription: Must be lowercase alphanumeric with hyphens only
  
  ProjectName:
    Type: String
    Description: Name of the GitHub repository (change this when copying to another repo)
    Default: my-app-repository
    MinLength: 1
    MaxLength: 100
    AllowedPattern: ^[a-zA-Z0-9._-]+$
    ConstraintDescription: Must be a valid GitHub repository name
  
  Environment:
    Type: String
    Description: Environment/Workspace (dev, stg, prod)
    AllowedValues:
      - dev
      - stg
      - prod
    Default: dev
  
  OIDCProviderStackName:
    Type: String
    Description: Name of the stack that deployed the GitHub OIDC provider
    Default: github-identity-provider
  
  TerraformAccessPolicyAccountID:
    Type: String
    Description: The account ID for Terraform access managed policy (from terraform-core-aws stack)

# Mapping from lower to upper as CFT does not have intrinsic functions for string case conversion
Mappings:
  EnvironmentMap:
    dev:
      Upper: DEV
    stg:
      Upper: STG
    prod:
      Upper: PROD

Resources:
  # IAM role for GitHub Actions (repository-specific)
  GitHubActionsRole:
    Type: AWS::IAM::Role
    Properties:
      # Role name will be auto-generated by CloudFormation with stack name prefix
      # This ensures uniqueness and follows AWS naming best practices
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Sub 
                - 'arn:aws:iam::${AWS::AccountId}:oidc-provider/token.actions.githubusercontent.com'
                - {}
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringLike:
                token.actions.githubusercontent.com:sub: !Sub 'repo:${Organization}/${ProjectName}:*'
              StringEquals:
                token.actions.githubusercontent.com:aud: sts.amazonaws.com
      ManagedPolicyArns:
        # REQUIRED: SSM parameter read policy to retrieve Terraform backend configuration
        - !Sub 'arn:aws:iam::${TerraformAccessPolicyAccountID}:policy/terraform-core-aws-tf-access-dev'
        # ADD YOUR APPLICATION-SPECIFIC MANAGED POLICIES BELOW
        # Examples:
        # - arn:aws:iam::aws:policy/ReadOnlyAccess
        # - !Sub 'arn:aws:iam::${AWS::AccountId}:policy/my-custom-policy'
      # ADD INLINE POLICIES HERE IF NEEDED
      # Policies:
      #   - PolicyName: application-specific-policy
      #     PolicyDocument:
      #       Version: '2012-10-17'
      #       Statement:
      #         - Effect: Allow
      #           Action:
      #             - s3:GetObject
      #             - s3:PutObject
      #           Resource: !Sub 'arn:aws:s3:::my-bucket/*'
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Organization
          Value: !Ref Organization
        - Key: Environment
          Value: !Ref Environment
        - Key: RepositoryURL
          Value: !Sub 'https://github.com/${Organization}/${ProjectName}'
        - Key: Automation
          Value: CloudFormation
        - Key: RepositoryPath
          Value: cloudformation/templates
        - Key: RepositoryFile
          Value: github-iam-role.yaml
        - Key: Description
          Value: !Sub 'IAM role for GitHub Actions in ${Organization}/${ProjectName}'
        - Key: Region
          Value: !Ref 'AWS::Region'

Outputs:
  AwsId:
    Value:
      Fn::Join:
        - ''
        - - !FindInMap [EnvironmentMap, !Ref Environment, Upper]
          - '_AWS_ID = '
          - !Ref 'AWS::AccountId'
  RoleSecret:
    Value:
      Fn::Join:
        - ''
        - - !FindInMap [EnvironmentMap, !Ref Environment, Upper]
          - '_ROLE_SECRET = '
          - Fn::Select:
              - 7
              - Fn::Split:
                  - "-"
                  - !GetAtt GitHubActionsRole.Arn
